import time
import random
from celery import shared_task
from .models import ProcessingTask

@shared_task(bind=True, max_retries=3)
def process_media_task(self, task_id):
    try:
        task = ProcessingTask.objects.get(id=task_id)
        task.status = 'processing'
        task.save()

        # Simulate a transient failure to demonstrate retries
        if random.random() < 0.2:  # 20% chance to fail and retry
            raise Exception("Simulated transient failure")

        # Mock processing delay
        time.sleep(5)

        result = {}
        input_data = task.input_data

        if task.task_type == 'text_summarization':
            text = input_data.get('text', '')
            result = {'summary': f"Summarized {len(text)} characters into a short sentence."}
        elif task.task_type == 'sentiment_analysis':
            result = {'sentiment': random.choice(['Positive', 'Negative', 'Neutral']), 'score': round(random.uniform(0, 1), 2)}
        elif task.task_type == 'image_captioning':
            result = {'caption': "A beautiful scenery generated by mock AI.", 'confidence': 0.95}
        else:
            result = {'output': "Mock result for unknown task type"}

        task.result_data = result
        task.status = 'completed'
        task.save()

        return f"Task {task_id} completed successfully."

    except ProcessingTask.DoesNotExist:
        return f"Task {task_id} not found."
    except Exception as exc:
        try:
            # Retry the task with exponential backoff
            raise self.retry(exc=exc, countdown=2 ** self.request.retries)
        except self.MaxRetriesExceededError:
            if 'task' in locals():
                task.status = 'failed'
                task.error_message = str(exc)
                task.save()
            return f"Task {task_id} failed: {str(exc)}"
